# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DoorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.DateTimeField(db_index=True)),
                ('closed', models.DateTimeField(blank=True, null=True)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_set', to='door.Door')),
            ],
            options={
                'ordering': ('-opened',),
            },
        ),
    ]
